### ISSUE TITLE
Crashing on Travis CI

### ISSUE THREAD

**Issue by madhavajay** [alexpls/SwiftLint-TravisCI-Example#1]
Hi, great script but it seems to cause Travis CI to crash immediately without any meaningful error.
Im kinda new to this though so maybe im just missing something obvious, any chance you can take a look?

https://travis-ci.org/symentis/Palau/builds/126323679
https://github.com/symentis/Palau/commit/7c0e456fe29da801f77663a876f6f05844f782d9

**Comment by alexpls** [comment]
I think your build might be crashing because the `install_swiftlint.sh` script does not have execute permissions on it. Without execute permissions Travis CI wouldn't be able to run it and install Swiftlint, and I think it would then just crash out.

To fix this you can try going to your command line and doing:

`$ chmod +x Resources/install_swiftlint.sh`

... then commit and hopefully it'll fix things up for you.

If that doesn't work let me know and reopen this issue.

**Comment by madhavajay** [comment]
Works like a dream, thanks for your help! 👍

**Comment by alexpls** [comment]
Great to hear!
